### ISSUE TITLE
The program crashes without "--debug" flag being set when using Cuda.

### ISSUE THREAD

**Issue by MhYao2014** [diningphil/gnn-comparison#11]
Is the "--debug"  flag a must when I use Cuda? I try to launch the experiments using both multi-thread and Cuda. But, why the program crashes when I leave " --debug" being empty, and it runs as expected when I set this flag? Does it imply that I can't use multi-thread when I use Cuda?

**Comment by diningphil** [comment]
Yes, --debug is required when using cuda. 
You can run experiments in parallel on CPUs only. This was a design choice driven by the availability of multiple CPUs and very few GPUs in our systems at the time of the experiments. 

Thank you for raising this point. I added an "Additional Notes" section in the Readme that specifies to use --debug when working with CUDA.
