### ISSUE TITLE
Using DGCNN with new data

### ISSUE THREAD

**Issue by ferdisvea** [diningphil/gnn-comparison#12]
Hi! Thanks for the awesome code. I have a question about DGCNN when using my own data. What is the k value in the configuration? I notice you have 0.6 and 0.9 and then a value for the specific number for the specific dataset, what does this correspond to? 
Thank you so much

**Comment by diningphil** [comment]
Hi,

*k* is the percentage of retained nodes by the SortPool layer. 
Please have a look at the original [paper](https://www.aaai.org/ocs/index.php/AAAI/AAAI18/paper/download/17146/16755) for more details.
