### ISSUE TITLE
Using dropout in last layer

### ISSUE THREAD

**Issue by foxtrotmike** [diningphil/gnn-comparison#14]
Thank you for the very useful repo. I noticed that you use dropout at the output layer in https://github.com/diningphil/gnn-comparison/blob/master/models/graph_classifiers/GIN.py. Is this for ensuring that all GIN layers contribute to the output?

**Comment by diningphil** [comment]
Hi,
I would suggest that you ask to the authors of the GIN paper to get an informed response. On our side, we just did our best to make the implementation as close as the one in the original repo. Please check the last lines of https://github.com/weihua916/powerful-gnns/blob/master/models/graphcnn.py for reference. Hope this helps.
