### ISSUE TITLE
Call each other

### ISSUE THREAD

**Issue by rym21** [diningphil/gnn-comparison#15]
In Launch_Experiments.py， def train() and def _train(), The two functions call each other, resulting in an endless loop?

**Comment by diningphil** [comment]
There is no definition of method train and _train in Launch_Experiments.py. What functions are you referring to?

**Comment by rym21** [comment]
The reason I suspect they call each other is because the program print to much logs and take a long time. I doubt that the program seems to be stuck in an endless loop and TE loss: None TE acc: None. I have changed classifier_epochs from 5000 to 50 in config_BaselineChemical.yml. I had the program running all night, and it give me a result. I have no problem now. Thanks for your attention.
