### ISSUE TITLE
additional features

### ISSUE THREAD

**Issue by pursueorigin** [diningphil/gnn-comparison#16]
https://github.com/diningphil/gnn-comparison/blob/5722c3cf5c10a31902768c2be9dc6403e4ba15d4/datasets/data.py#L18

What is the purpose of these additional features? Where are they used in this project? Thanks.

**Comment by diningphil** [comment]
These are used to experiment with a model of mine called [Contextual Graph Markov Model](https://github.com/diningphil/CGMM), which is not present in this repository. You can ignore them as they are never used.
