### ISSUE TITLE
Is there a mistake in Data Preprocessing?

### ISSUE THREAD

**Issue by JindongGu** [diningphil/gnn-comparison#2]
In the 42th row of the file https://github.com/diningphil/gnn-comparison/blob/master/datasets/tu_utils.py

    with open(edges_path, "r") as f:
        for i, line in enumerate(f.readlines(), 1):
            line = line.rstrip("\n")
            edge = [int(e) for e in line.split(',')]
            edge_indicator.append(edge)
            graph_id = indicator[edge[0]]
            graph_edges[graph_id].append(edge)

graph_id = indicator[edge[0]]     should be  graph_id = indicator[i]  in order to get the right graph_id ?

edge[0] means the index of the starting node of an edge.

**Comment by marcopodda** [comment]
Hi,
``edge[0]`` contains a node_id. ``indicator[edge[0]]`` maps the node_id to the associated graph_id using the graph indicator file. As per the readme:

(2)   DS_graph_indicator.txt (n lines)
  column vector of graph identifiers for all nodes of all graphs, the value in the i-th line is the graph_id of the node with node_id i.

Therefore, the preprocessing is correct. Also, note that ``edge[0]`` does not necessarily reflect the source node of the edge; it depends on the assumption made in the adjacency list file.

Thanks for pointing out this ambiguity, we have added appropriate comments to clarify.

**Comment by JindongGu** [comment]
> Therefore

Thank you for your explanations. I misunderstood the dataset.

Also thank you for your nice contributions, these fair comparisons of GNNs is of significance to our community.
