### ISSUE TITLE
Can't find device = cuda in config files

### ISSUE THREAD

**Issue by YoavLotem** [diningphil/gnn-comparison#43]
Hi team :) 
Thanks for this great work!

I was wondering why doesn't the configuration files contain cuda as a possible device option even though the paper mentions it as a possible device?

For example here are two images from GraphSAGE config file and from the paper:
![image](https://github.com/diningphil/gnn-comparison/assets/87936902/ee5c599b-adf5-44fe-bc08-d9c9a5074166)
![image](https://github.com/diningphil/gnn-comparison/assets/87936902/3392809c-c712-4c6c-8f8b-fa0e4535636e)

Thank you in advance!
@Zmeos @diningphil @marcopodda @dbacciu

**Comment by diningphil** [comment]
Hi,

If you want to use cuda, just change the configuration file from `cpu` to `cuda`. We did not specify it in the public file because we do not know if your pc has cuda installed.

Best regards,
Federico
