### ISSUE TITLE
GraphSage doesn't learn.

### ISSUE THREAD

**Issue by ssantos97** [diningphil/gnn-comparison#50]
Hi, I followed all the instructions in the github but turns out that when I'm trying to train the GraphSAGE for Social-1/IMDB-BINARY and Social-DEGREE/IMDB-BINARY the accuracies don't go higher than 0.5 (including training acc) which shows that the predictions are random. The same thing does not happen for GIN where the accuracies increase.

Pytorch 2.0.1
torch-geometric 2.3.1
python 3.10.10

**Comment by ssantos97** [comment]
The outputs of the forward for GraphSAGE are all equal for the same iteration, which I think makes sense since the features are all 1.

**Comment by ssantos97** [comment]
Also ouputs after first layer(x, edge_index) is all equal for the same training iterations.

**Comment by ssantos97** [comment]
Same thing occurs for IMDB-MULTI, the accuracies don't go higher than 30%

**Comment by diningphil** [comment]
Hi, I'm investigating. It's possible it has to do with the newer version of PyG compared to 2020. Have you tried other social/chemical datasets rather than IMDB?

**Comment by ssantos97** [comment]
I ran the same exatc commands and the error persists :(

**Comment by ssantos97** [comment]
Deleted the folder Data and ran the commands you mention and now it seemds to work. I don't know what was blocking it from learning but anyways thank you.

**Comment by diningphil** [comment]
I''m baffled as well.. happy to help! :)

**Comment by ssantos97** [comment]
- `python PrepareDatasets.py DATA/SOCIAL_1 --dataset-name IMDB-BINARY --use-one --outer-k 10
- cp -r DATA/SOCIAL_1/IMDB-BINARY/ DATA
- python Launch_Experiments.py --config-file config_GraphSAGE.yml --dataset-name IMDB-BINARY --result-folder RESULTS --debug`

For SOCIAL_1 keeps not working :(

**Comment by ssantos97** [comment]
And this happens for all social datasets with use_one

**Comment by diningphil** [comment]
Thanks for raising the problem. Apparently setting `conv.aggr` after initialization does not work anymore, so I updated the code and now GraphSAGE learns with "add" aggregation on SOCIAL_1 IMDB-BINARY.

Please pull and retry!

**Comment by ssantos97** [comment]
Working now. Thank you.
